import Head from "next/head";
import { Button } from "react-bootstrap";
import { useSelector, useDispatch } from "react-redux";

import { firstActions } from "../store/slices/first";
import { secondActions } from "../store/slices/second";

export default function Home() {
    const dispatch = useDispatch();
    const counter = useSelector((state) => state.first.counter);
    const authValue = useSelector((state) => state.second.isLogin);

    const changeAuthHandler = () => {
        dispatch(secondActions.setIsLogin());
    };

    const incCounterHandler = () => {
        dispatch(firstActions.increment({ amount: 1 }));
    };

    const inc5CounterHandler = () => {
        dispatch(firstActions.increment({ amount: 5 }));
    };

    const decCounterHandler = () => {
        dispatch(firstActions.decrement({ amount: 1 }));
    };

    const dec5CounterHandler = () => {
        dispatch(firstActions.decrement({ amount: 5 }));
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>{counter}</div>
            <div>{authValue ? "yes" : "no"}</div>
            <br />
            <Button variant="info" onClick={changeAuthHandler}>
                change auth
            </Button>
            <br />
            <br />
            <Button variant="success" onClick={incCounterHandler}>
                +1
            </Button>{" "}
            <Button variant="success" onClick={inc5CounterHandler}>
                +5
            </Button>{" "}
            <Button variant="danger" onClick={decCounterHandler}>
                -1
            </Button>{" "}
            <Button variant="danger" onClick={dec5CounterHandler}>
                -5
            </Button>{" "}
        </div>
    );
}
